version: "3"
services:
  offender-events-ui:
    build: .
    container_name: offender-events-ui
    depends_on:
      - localstack
    ports:
      - "8095:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SQS_ENDPOINT_URL=http://localhost:4566
      - SPRING_PROFILES_ACTIVE=localstack
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobar
      - AWS_DEFAULT_REGION=eu-west-2

  offender-events-ui-db:
    image: redis:7.0
    networks:
      - hmpps
    container_name: offender-events-ui-db
    restart: always
    ports:
      - '6379:6379'

  localstack:
    image: localstack/localstack:2.3
    networks:
      - hmpps
    container_name: localstack
    ports:
      - "4566:4566"
      - 8999:8080
    environment:
      - SERVICES=sns,sqs
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"

networks:
  hmpps:
