---
# Values here are the same across all environments
generic-service:
  nameOverride: offender-events-ui

  image:
    repository: quay.io/hmpps/offender-events-ui
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    tlsSecretName: offender-events-ui-cert

  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    SPRING_REDIS_SSL: "true"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    offender-events-ui:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
    oeu-sqs-instance-output:
      HMPPS_SQS_QUEUES_EVENT_QUEUE_NAME: "sqs_ptpu_name"
      HMPPS_SQS_QUEUES_EVENT_QUEUE_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_EVENT_QUEUE_SECRET_ACCESS_KEY: "secret_access_key"
    oeu-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_EVENT_DLQ_NAME: "sqs_ptpu_name"
      HMPPS_SQS_QUEUES_EVENT_DLQ_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_QUEUES_EVENT_DLQ_SECRET_ACCESS_KEY: "secret_access_key"
    offender-events-ui-elasticache-redis:
      SPRING_REDIS_HOST: "primary_endpoint_address"
      SPRING_REDIS_PASSWORD: "auth_token"

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"

generic-prometheus-alerts:
  targetApplication: offender-events-ui
