---
# Environment specific values, override helm_deploy/court-register/values.yaml
generic-service:
  replicaCount: 1
  ingress:
    host: offender-events-ui-dev.prison.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"
    delius-aws-1: "52.56.240.62/32"
    delius-aws-2: "18.130.110.168/32"
    delius-aws-3: "35.178.44.184/32"
    delius-aws-perf-1: "3.10.200.35/32"
    delius-aws-perf-2: "3.11.166.247/32"
    delius-aws-perf-3: "52.56.136.138/32"
    analyticplatform-1: "34.250.17.221/32"
    analyticplatform-2: "34.251.212.33/32"
    analyticplatform-3: "34.252.4.39/32"
    unilink-aovpn1: "194.75.210.216/29"
    unilink-aovpn2: "83.98.63.176/29"
    unilink-aovpn3: "78.33.10.50/31"
    unilink-aovpn4: "78.33.10.52/30"
    unilink-aovpn5: "78.33.10.56/30"
    unilink-aovpn6: "78.33.10.60/32"
    unilink-aovpn7: "78.33.32.99/32"
    unilink-aovpn8: "78.33.32.100/30"
    unilink-aovpn9: "78.33.32.104/30"
    unilink-aovpn10: "78.33.32.108/32"
    unilink-aovpn11: "217.138.45.109/32"
    unilink-aovpn12: "217.138.45.110/32"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: syscon
  sqsAlertsQueueNames:
    - "Digital-Prison-Services-dev-offender_events_ui_queue"
    - "Digital-Prison-Services-dev-offender_events_ui_queue_dl"
  sqsAlertsOldestThreshold: 2
  sqsAlertsTotalMessagesThreshold: 1
