---
# Environment specific values, override helm_deploy/court-register/values.yaml
generic-service:
  replicaCount: 1
  ingress:
    host: offender-events-ui-dev.prison.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json


# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
